# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/airnz',
                'doc_host': 'https://weiyunnaopenai.github.io',
                'git_url': 'https://github.com/weiyunnaopenai/airnz',
                'lib_path': 'airnz'},
  'syms': {'airnz.core': {'airnz.core.foo': ('core.html#foo', 'airnz/core.py')}}}
